### ISSUE TITLE
Shattered Mirror

### ISSUE THREAD

**Issue by EnderGrimm1** [cheeeeeeeeeen/RoR2-ClassicItems#17]
i of thought of a method for how Shattered Mirror could be transferred over to 3D - for the active period you have a friendly doppleganger (from that one artifact) at the end of the duration it dies. If the equipment is doubled or used again before the duration is over the duration is extended

**Comment by cheeeeeeeeeen** [comment]
Related discussion: #23 
This will be moved there until it becomes official; re-open when it's official to be implemented.
