### ISSUE TITLE
mod loader issue.

### ISSUE THREAD

**Issue by GenesisFuz** [cheeeeeeeeeen/RoR2-ClassicItems#32]
### Describe the Bug
can't download the mod on the manager, it freezes it when ever i try.

### To Reproduce
1. Go to mod manager
2. Click on your mod
3. download
4. and apply. 

### Expected Behavior
Freezes the client once you click apply and it tries to download and install the mod.

**Comment by cheeeeeeeeeen** [comment]
Please go ask in Discord about this issue. This is most likely r2modman's issue. Closing.
