### ISSUE TITLE
Arms Race [Config Option]

### ISSUE THREAD

**Issue by Coffe-e** [cheeeeeeeeeen/RoR2-ClassicItems#4]
Arms Race I feel, should work with certain allies [Squid Polyp, specifically], but because it's meant for drones, I don't think it'd fit into the mod as the default functionality.

**Comment by cheeeeeeeeeen** [comment]
I'll try. It's just that Squid Polyp isn't machine, and is organic.

**Comment by Coffe-e** [comment]
Yeah. I get that. Thanks for considering it though!

**Comment by cheeeeeeeeeen** [comment]
This is now implemented.
