### ISSUE TITLE
Thallium debuff not doing anything on players.

### ISSUE THREAD

**Issue by Coffe-e** [cheeeeeeeeeen/RoR2-ClassicItems#5]
### Describe the Bug
When the thallium item is gotten by enemies, the debuff doesn't affect players.

### To Reproduce
1. Turn on Evolution Artifact,
2. Wait until they get Thallium
3. Get the debuff inflicted on you

### Expected Behavior
Players should experience the effects of the debuff.

**Comment by cheeeeeeeeeen** [comment]
I tested. I got the Thallium debuff and I got poisoned, and died to it.

**Comment by cheeeeeeeeeen** [comment]
Video: https://streamable.com/w8vco8

**Comment by cheeeeeeeeeen** [comment]
@Coffe-e Re-open this issue if you still experience the bug. If able, send a video. Closing now.

**Comment by Coffe-e** [comment]
Oh, my bad. I realized that when I was testing certain things, I was actually in god mode. 
Sorry about that!
