### ISSUE TITLE
Suggestions: Add Toxic Worm

### ISSUE THREAD

**Issue by EnderGrimm1** [cheeeeeeeeeen/RoR2-ClassicItems#9]
Toxic Worm to cycle between the names Toxic Worm and Centipede to elude to the bug from the first game.

This one is a bit of a stretch but would be cool if alongside the Ifrit's Horn item you added Ifrit as a boss you can run into.

**Comment by cheeeeeeeeeen** [comment]
New scope: Only implement Toxic Worm. I will be updating the issue title to reflect this.

**Comment by cheeeeeeeeeen** [comment]
Related discussion: #25 
This will be moved there until it becomes official; re-open when it's official to be implemented.
